---
abstract: 'Easy access to Consul (http://www.consul.io/)'
author:
  - 'Dana M. Diederich <dana@realms.org>'
build_requires:
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Consul-Simple
requires:
  Data::Dumper: 0
  HTTP::Request::Common: 0
  HTTP::Response: 0
  JSON: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dana/perl-Consul-Simple/issues
  homepage: https://github.com/dana/perl-Consul-Simple
  repository: https://github.com/dana/perl-Consul-Simple.git
version: 1.142390
